### PR TITLE
add blogroll for r-bloggers

### PR DESCRIPTION
**Pull request by pat-s**
Requirement to list our blog in r-bloggers again.

Haven't done a preview but I think it's fine?

### CODE REVIEW

**Comment by sebffischer** [comment]
sorry forgot to check, I think we should directly add the link, the intermediate site is kind of unnecessary

**Comment by pat-s** [comment]
Where would you add it? It's just for ad purposes, nothing users are interested in.

**Comment by sebffischer** [comment]
I just mean that when you click on the button "Blogroll" you should directly be redirected to R-bloggers.

**Comment by pat-s** [comment]
A "blogroll" is a list, usually consisting of multiple blogs which are "recommended" to read. We could add more there, it's just that r-bloggers enforces it.

**Pull request merged**
