### PR TITLE
Move from Distill to Quarto

### PR DESCRIPTION
**Pull request by pat-s**
@be-marc @sebffischer @mllg 
This is a first draft of a `quarto` based version of the website. There's still some things to do but you can checkout this branch and have a first look yourself.

Feel free to list/discuss any suggestions/dislikes from your side here.

Preview: https://teal-mooncake-1d874f.netlify.app/

## TODO

- [x] check all gallery and blog posts
- [x] fix citations
- [x] fix grid view of "packages"
- [x] fix md links in "pipelines"
- [x] add sites for all team members
- [x] fix "resources" section on main page

## Rendering

- Replace `eval_all: FALSE` by `eval_all: TRUE` (to create all one-time calculations)
- `quarto preview .`

### CODE REVIEW

**Comment by sebffischer** [comment]
great, I will check it out today! 
Do you want to discuss it tomorrow?

**Comment by pat-s** [comment]
@sebffischer Fixed some small stuff, maybe rendering now works for you?

**Comment by pat-s** [comment]
@be-marc @sebffischer @mllg "production ready": https://teal-mooncake-1d874f.netlify.app/

**Comment by be-marc** [comment]
Before merge

* Add package overview
* Gallery post view like blog

**Pull request merged**
