### PR TITLE
Add tab "more" and rename "Learn mlr3" to "Resources"

### PR DESCRIPTION
**Pull request by sebffischer**

### CODE REVIEW

**Review by pat-s — COMMENTED** [review]
Thanks! I like the linking to the quarterly update post!

More restructuring and linking to existing resources is definitely good and needed 👍 

Could you post a screenshot of how the header looks like then? We don't have a preview anymore and I am arguably too lazy to render it myself 👀

**Comment by sebffischer** [comment]
Screenshot from 2022-04-25 12-09-31

**Comment by pat-s** [comment]
Given that we have so much space in the navbar - should we maybe put just all items next to each other and omit using a dropdown?

**Comment by sebffischer** [comment]
Hmm not sure why it looks like that in the screenshot but https://mlr-org.com/ seems to be fine  (i.e. not too much space)?

**Comment by pat-s** [comment]
Maybe we misunderstand each other. I was referring to the empty space in the navbar between "overview" and the search menu.

If we put the items grouped in "more" as single items, we could make use of that space? Just an idea though..

**Pull request merged**
